-- Create new db_user in Oracle database and grant permissions. 
CREATE USER db_user IDENTIFIED BY db_pwd;
-- ALTER USER schema_user_name IDENTIFIED BY schema_password;

GRANT CONNECT TO db_user;
GRANT ALTER ANY TABLE TO db_user;
GRANT CREATE TABLE TO db_user;
GRANT DROP ANY TABLE TO db_user;
GRANT CREATE ANY VIEW TO db_user;
GRANT DROP ANY VIEW TO db_user;
GRANT CREATE MATERIALIZED VIEW TO db_user;
GRANT DROP ANY MATERIALIZED VIEW TO db_user;
GRANT ALTER ANY MATERIALIZED VIEW TO db_user;
GRANT CREATE PROCEDURE TO db_user;
GRANT ALTER ANY PROCEDURE TO db_user;
GRANT DROP ANY PROCEDURE TO db_user;
GRANT EXECUTE ANY PROCEDURE TO db_user;
GRANT CREATE SYNONYM TO db_user;
GRANT DROP PUBLIC SYNONYM TO db_user;
GRANT CREATE SEQUENCE TO db_user;
GRANT ALTER ANY SEQUENCE TO db_user;
GRANT DROP ANY SEQUENCE TO db_user;
GRANT CREATE DATABASE LINK TO db_user;
GRANT CREATE PUBLIC DATABASE LINK TO db_user;
GRANT DROP PUBLIC DATABASE LINK TO db_user;
GRANT CREATE SESSION TO db_user;
GRANT UNLIMITED TABLESPACE TO db_user;
